### ISSUE TITLE
how to use pointcloud ?

### ISSUE THREAD

**Issue by lonlonago** [TimKie/YOLO-LiDAR-Fusion#1]
What role does the point cloud data obtained according to the segmentation result play in the end?

 I looked at the code. It seems that after the 3D points of the point cloud are finally extracted, they are only used for projection display, and are not used for other purposes?

thanks!

**Comment by TimKie** [comment]
Hello,

Yes, in the code, the results obtained from the [`process_data`](https://github.com/TimKie/YOLO-LiDAR-Fusion/blob/851003490d998f4c3e6ccf61d42a8738a72c535a/Code/detector.py#L14) function are primarily used for the visualization.  However, you can also use the [`ROS_ground_center`](https://github.com/TimKie/YOLO-LiDAR-Fusion/blob/851003490d998f4c3e6ccf61d42a8738a72c535a/Code/detector.py#L70), [`ROS_dimensions`](https://github.com/TimKie/YOLO-LiDAR-Fusion/blob/851003490d998f4c3e6ccf61d42a8738a72c535a/Code/detector.py#L71) or [`ROS_points`](https://github.com/TimKie/YOLO-LiDAR-Fusion/blob/851003490d998f4c3e6ccf61d42a8738a72c535a/Code/detector.py#L72) for example, to further process the 3D bounding boxes.

This data (and other relevant information) could, for example, be published on a ROS2 topic to enable a motion planner to process it and update the vehicle’s trajectory accordingly.

**Comment by lonlonago** [comment]
got it , thanks for your replay!
