### ISSUE TITLE
Hello author，I really need your help now

### ISSUE THREAD

**Issue by haiyaoduojiu111111** [TimKie/YOLO-LiDAR-Fusion#2]
I recently want to write an article about the fusion of vision and LiDAR for target recognition. I have read your project and think your code is very good. Is there any corresponding academic paper to support this open source project? If you can provide it to me, I will be very grateful to you. Thank you

**Comment by TimKie** [comment]
Hello,

Thank you for your interest in the project. I now added the corresponding academic [paper](https://github.com/TimKie/YOLO-LiDAR-Fusion/blob/fad44530dcfa172145f67ce0469d7b29bcd02bda/Master_Thesis_compressed.pdf) to the repository.

**Comment by haiyaoduojiu111** [comment]
> 你好
> 
> 感谢您对该项目的关注。我现在将相应的学术[论文](https://github.com/TimKie/YOLO-LiDAR-Fusion/blob/fad44530dcfa172145f67ce0469d7b29bcd02bda/Master_Thesis_compressed.pdf)添加到存储库中。
You are awesome, thank you so much！！！

**Comment by haiyaoduojiu111** [comment]
You are awesome, thank you so much！！！
